name: Build

on:
  push:
    branches:
      - main
    paths-ignore: [ 'Doc/**', 'Flights/**', 'Html/**', 'Images/**', 'Localdoc/**', 'Scenarios/**', 'Textures/**', 'Textures2/**']
  pull_request:
    branches:
      - main
    paths-ignore: [ 'Doc/**', 'Flights/**', 'Html/**', 'Images/**', 'Localdoc/**', 'Scenarios/**', 'Textures/**', 'Textures2/**']

jobs:
  build:
    name: Build with CMake
    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 2
    strategy:
      fail-fast: false
      matrix:
        architecture: [x64, Win32]
      
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup Problem Matcher
      uses: ammaraskar/msvc-problem-matcher@master
      
    - name: Prepare
      run: |
        mkdir out\build
        mkdir out\install
      
    - name: Configure
      run: 'cmake -A ${{ matrix.architecture }} -G "Visual Studio 16 2019" -S ../.. -DORBITER_MAKE_DOC=OFF -DHTML_HELP_LIBRARY="C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\um\x86\Htmlhelp.Lib"'
      working-directory: ${{ github.workspace }}/out/build

    - name: Build
      run: 'cmake --build . --config Release -- "-maxCpuCount:2" /p:CL_MPcount=2'
      working-directory: ${{ github.workspace }}/out/build

    - name: Test
      run: 'ctest --build-config Release'
      working-directory: ${{ github.workspace }}/out/build

    - name: Install
      run: 'cmake --install . --prefix "${{ github.workspace }}\out\install"'
      working-directory: ${{ github.workspace }}/out/build

    - name: Pack
      if: ${{ github.ref == 'refs/heads/main' }}
      working-directory: ${{ github.workspace }}/out/install/Orbiter
      shell: cmd
      run: '7z a "${{ github.workspace }}/out/Orbiter.zip" .'

    - name: Upload Build Artifact
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: actions/upload-artifact@v2.2.4
      with:
        name: Orbiter-${{ matrix.architecture }}
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{ github.workspace }}/out/Orbiter.zip
        retention-days: 60
