name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'Doc/**'
      - 'Flights/**'
      - 'Html/**'
      - 'Images/**'
      - 'Localdoc/**'
      - 'Scenarios/**'
      - 'Textures/**'
      - 'Textures2/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'Doc/**'
      - 'Flights/**'
      - 'Html/**'
      - 'Images/**'
      - 'Localdoc/**'
      - 'Scenarios/**'
      - 'Textures/**'
      - 'Textures2/**'

jobs:
  build:
    name: Build with CMake
    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 2
      VCToolsInstallDir: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\"
    strategy:
      fail-fast: false
      matrix:
        architecture: [x64, x86]
      
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Prepare
      run: |
        mkdir out\build
        mkdir out\install
      
    - name: Build & Test
      shell: cmd
      continue-on-error: true
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" ${{ matrix.architecture }}
        cmake --preset ${{ matrix.architecture }}-release -DORBITER_MAKE_DOC=OFF
        cmake --build --preset build-${{ matrix.architecture }}-release
        ctest --preset test-${{ matrix.architecture }}-release

    - name: Install
      run: cmake --install . --prefix  ${{ github.workspace }}/out/install
      working-directory: ${{ github.workspace }}/out/build/${{ matrix.architecture }}-release

    - name: Pack
      if: ${{ github.ref == 'refs/heads/main' && matrix.architecture == 'x64' }}
      working-directory: ${{ github.workspace }}/out/install/Orbiter
      shell: cmd
      run: '7z a "${{ github.workspace }}/out/Orbiter.zip" .'

    - name: Upload Build Artifact
      if: ${{ github.ref == 'refs/heads/main' && matrix.architecture == 'x64' }}
      uses: actions/upload-artifact@v2.2.4
      with:
        name: Orbiter-${{ matrix.architecture }}
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{ github.workspace }}/out/Orbiter.zip
        retention-days: 7
